services:
  mysql:
    image: mysql:latest
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tododb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: todo-backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: todo-mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: tododb
    ports:
      - "8080:8080"

volumes:
  mysql_data:
